<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <ItemGroup>
    <ProjectReference Include="..\Pmcro.Runtime\Pmcro.Runtime.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>a75ee3ba-e7b8-466d-8838-b6370f4b7b68</UserSecretsId>
  </PropertyGroup>

</Project>
