FROM mcr.microsoft.com/dotnet/sdk:{{DotnetVersion}} AS build
WORKDIR /src
COPY *.csproj ./
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/runtime:{{DotnetVersion}}
WORKDIR /app
COPY --from=build /app .
USER app
ENTRYPOINT ["dotnet", "{{ProjectName}}.dll"]
