<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <UserSecretsId>39b36bc9-7701-4f00-9236-8757d424a950</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Agents.AI.DevUI" />
    <PackageReference Include="Microsoft.Agents.AI.Hosting" />
    <PackageReference Include="Microsoft.Agents.AI.Hosting.OpenAI" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" />
    <PackageReference Include="OpenTelemetry.Api" />
    <PackageReference Include="CommunityToolkit.Aspire.OllamaSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pmcro.ServiceDefaults\Pmcro.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Pmcro.Tests" />
  </ItemGroup>

</Project>
